-- MySQL Script generated by MySQL Workbench
-- Sun Jan 14 20:52:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema suporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema suporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suporte` DEFAULT CHARACTER SET latin1 ;
USE `suporte` ;

-- -----------------------------------------------------
-- Table `suporte`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suporte`.`setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `prioridade` INT NOT NULL,
  PRIMARY KEY (`idSetor`),
  UNIQUE INDEX `idsetor_UNIQUE` (`idSetor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suporte`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suporte`.`tecnico` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` INT NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  `avaliacao` INT NULL,
  PRIMARY KEY (`idTecnico`),
  UNIQUE INDEX `idTecnico_UNIQUE` (`idTecnico` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suporte`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suporte`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `setor_idSetor` INT NOT NULL,
  `tecnico_idTecnico` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC),
  INDEX `fk_cliente_setor1_idx` (`setor_idSetor` ASC),
  INDEX `fk_cliente_tecnico1_idx` (`tecnico_idTecnico` ASC),
  CONSTRAINT `fk_cliente_setor1`
    FOREIGN KEY (`setor_idSetor`)
    REFERENCES `suporte`.`setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_tecnico1`
    FOREIGN KEY (`tecnico_idTecnico`)
    REFERENCES `suporte`.`tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suporte`.`chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suporte`.`chamado` (
  `idChamado` INT NOT NULL AUTO_INCREMENT,
  `nomeProblema` VARCHAR(100) NOT NULL,
  `descricaoProblema` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NULL,
  `posicao` INT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NULL,
  `avaliacao` INT NULL,
  `cliente_idCliente` INT NOT NULL,
  `tecnico_idTecnico` INT NOT NULL,
  PRIMARY KEY (`idChamado`),
  UNIQUE INDEX `idChamado_UNIQUE` (`idChamado` ASC),
  INDEX `fk_chamado_cliente1_idx` (`cliente_idCliente` ASC),
  INDEX `fk_chamado_tecnico1_idx` (`tecnico_idTecnico` ASC),
  CONSTRAINT `fk_chamado_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `suporte`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamado_tecnico1`
    FOREIGN KEY (`tecnico_idTecnico`)
    REFERENCES `suporte`.`tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
